"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
properties:
  homeserver:
    type: "object"
    properties:
      domain:
        type: "string"
      url:
        type: "string"
      mediaUrl:
        type: "string"
  web:
    type: "object"
    properties:
      bind:
        type: "string"
      port:
        type: "integer"
  webhookBot:
    type: "object"
    properties:
      appearance:
        type: "object"
        properties:
          displayName:
            type: "string"
          avatarUrl:
            type: "string"
  logging:
    type: "object"
    properties:
      file:
        type: "string"
      console:
        type: "boolean"
      consoleLevel:
        type: "string"
      fileLevel:
        type: "string"
      rotate:
        type: "object"
        properties:
          size:
            type: "number"
          count:
            type: "number"